export  const films = [
    {
        "id":1,
        "title":"asdasd",
        "duration":111,
        "price":35
    },
    {
        "id":2,
        "title":"QQwasdas",
        "duration":22,
        "price":44
    },
    {
        "id":3,
        "title":"xcvxcvx",
        "duration":66,
        "price":2235
    }
];